# Pokemon Card snapshot transformation

#### *This notebook is used to protype data processing before it is implement into a .py script.*
#### *This notebook is here for demonstration purposes and to understand how data preprocessing was done *

Previously, I scraped data from [bulbapedia (pokemon list data)](https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_National_Pok%C3%A9dex_number), [bulbapedia (pokemon sets data)](https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_Trading_Card_Game_expansions) and [tcgplayer (pokemon card data)](https://shop.tcgplayer.com/price-guide/pokemon). From these 3 sites I generated json files that contain the following:

 - **pokemon_list.json**
     - pokemon generic name - like in the pokedex that is already ordered
 - **pokemon_sets.json**
     - pokemon set name
     - pokemon set release date
     - pokemon set abbreviation
 - **pokemon_stats_date_scraped.json**
     - card name
     - card set
     - card number
     - card rarity
     - card type
     - pokemon HP
     - pokemon evolution stage
     - card median price
     - card foil median price
     - card market price
     - card foil market price
     - pokemon resistance
     - pokemon weakness
     - pokemon attack [1,2,3,4]
     - card text
     - web scraped date
     - card url
     
    - created columns
         - pokemon [1,2,3]
         - pokedex [1,2,3]
         - card id (surgate of card name, set and number)
         - set date
         - set abr
  
#### This notebook shows how data is imported and processed(combined, clearned and other common data wrangling tasks) to be saved as a single snapshot (this will be saved in an S3 bucket)

## Importing required libraries

In [1]:
import pandas as pd
import numpy as np
import json
import re
import os
from itertools import zip_longest
from datetime import date

## 1) processing the pokemon_list
    The pokedex is a list of every unique pokemon
    
#### **Cleaning guide:**
3 pokemon names were altered because they used special characters unlike the tcgplayer website

* Note that the pokedex is already in order

In [2]:
file_path = f'C:/Users/jonny/programming_content/pokemon_cards/data_extracting/pokemon_cards/pokemon_cards/scraped_data/pokemon_list_2020-03-24.json'
with open(file_path) as f:
    raw_data = json.load(f)
pokemon_list = raw_data[0]['pokemon_list']
pokemon_list[28] = 'Nidoran F'
pokemon_list[31] = 'Nidoran M'
pokemon_list[668] = 'Flabebe'

pokemon_list_df = pd.DataFrame(data = pokemon_list, columns = ['Pokemon Name'])
pokemon_list_df.head()

  Pokemon Name
0    Bulbasaur
1      Ivysaur
2     Venusaur
3   Charmander
4   Charmeleon

## 2) processing pokemon_sets 
    contains the following:
    
    Set name: official expansion name
    Set date: When set was released
    Set abr: Abbreviation of the set name
    
#### **Cleaning guide:**
- There were 2 sets that were released in japan but no in English. blank lines were created and therefore removed
- The set name had '&' changed to 'and' to follow the format from tcg player sets
- A filler element is appended if the newest pokemon set name is known but the release date or abr is not

In [3]:
file_path = f'C:/Users/jonny/programming_content/pokemon_cards/data_extracting/pokemon_cards/pokemon_cards/scraped_data/pokemon_sets_2020-03-24.json'
with open(file_path) as f:
    raw_data = json.load(f)

set_name = raw_data[0]['set_name']
set_date =  raw_data[0]['set_date']
set_abr = raw_data[0]['set_abbreviation']

# removes blank lines
set_name = list(filter(None, set_name))
set_date = list(filter(None, set_date))
set_abr = list(filter(None, set_abr))

# sometimes a new set is known but the abr or release date is not
if len(set_date) < len(set_name):
    set_date.append('')
if len(set_abr) < len(set_name):
    set_abr.append('')

pokemon_set_df = pd.DataFrame(np.array([set_name,set_date,set_abr]).T, columns = ['Set Name', 'Set Date' , 'Set Abr'])
pokemon_set_df['Set Name'] = pokemon_set_df['Set Name'].str.replace('&','and')
pokemon_set_df.tail()

            Set Name          Set Date Set Abr
84     Unified Minds    August 2, 2019     UNM
85      Hidden Fates   August 23, 2019     HIF
86    Cosmic Eclipse  November 1, 2019     CEC
87  Sword and Shield  February 7, 2020     SSH
88       Rebel Clash       May 1, 2020

## 3) pokemon card stats

Contains the folllowing parameters:
 - card surogate id (name, number, set)
 - card name
 - card number
 - card rarity
 - card type
 - card HP
 - card evolution stage
 - card median price
 - card foil median price
 - card market price
 - card foil market price
 - card resistance
 - card weakness
 - card attack [1,2,3,4]
 - card text
 - web scraped date
 - card url
     
    
#### **Cleaning guide:**

- Loading Data
- Adding a Card ID tag

In [96]:
file_path = f'C:/Users/jonny/programming_content/pokemon_cards/data_extracting/pokemon_cards/pokemon_cards/scraped_data/pokemon_cards_2020-03-24.json'
df = pd.read_json(file_path)
df.head(2)

,Card Name,Set Name,Card Number,Rarity,Card Type,HP,Stage,Card Text,Attack 1,Weakness,...,Median Price Foil,Url,Scraped Date,Market Price Normal,Median Price Normal,Attack 2,,Attack 3,Attack 4,Presale Information
0,Zamazenta V (Secret),SWSH01: Sword & Shield Base Set,212/202,Secret Rare,Metal,230.0,Basic,Ability — Dauntless ShieldPrevent all damage d...,[1MM] Assault Tackle (130)Discard a Special En...,Rx2,...,$21.24,https://shop.tcgplayer.com/pokemon/swsh01-swor...,2020-03-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Water Energy (2004-2005),Professor Program Promos,106/109,Promo,Energy,NaN,NaN,NaN,NaN,NaN,...,NaN,https://shop.tcgplayer.com/pokemon/professor-p...,2020-03-24,N/A,$19.97,NaN,NaN,NaN,NaN,NaN

### Checking NA values for all pokemon cards
- shows Card Name, a Set Name and a Rarity are all filled
- card number is mostly filled

In [97]:
df.dropna(subset=['Card Name'], inplace = True)
df.drop(columns = ['Presale Information'], inplace = True)
df.reset_index(inplace = True)

In [98]:
df.isna().sum()

index                      0
Card Name                  0
Set Name                   0
Card Number               99
Rarity                     0
Card Type                325
HP                      2124
Stage                   2140
Card Text               9242
Attack 1                2190
Weakness                2672
Resistance              5170
Retreat Cost            2615
Market Price Foil       2146
Median Price Foil       2146
Url                        0
Scraped Date               0
Market Price Normal     4638
Median Price Normal     4638
Attack 2                6782
                       13813
Attack 3               13954
Attack 4               14308
dtype: int64

### all the unique pokemon stage names
This is useful since stage name can divide pokemon and non pokemon categories

In [99]:
df.loc[:,'Stage'].unique()

array(['Basic', nan, 'Stage 1', 'BREAK Evolution', 'Stage 2', 'Mega',
       'Mega Evolution', 'Item', 'Special Energy', 'Supporter',
       'Restored', 'Tool', 'Stadium', 'Energy', 'Trainer', 'VMAX',
       'Gigantamax', 'Technical Machine', 'Level Up', 'Baby', '',
       'Legend', 'Primal', '2', '1', 'Basic — Ultra Beast', 'bASIC'],
      dtype=object)

In [100]:
# seperate by stage
not_pokemons_keys = ['Energy', 'Trainer', 'Special Energy','Stadium','Technical Machine', 'Item','', 'Tool', 'Supporter']
pokemon_bool_1 = ~df['Stage'].isin(not_pokemons_keys)
pokemon_bool_2 = ~df['Stage'].isna()
pokemon_bool = pokemon_bool_1 & pokemon_bool_2
df['Is Pokemon'] = pokemon_bool

### Minor cleaning
There are more errors to come. Most won't be addressed in this notebook. But for now, to get the right key values.
A future project that ensures data integrity by:
- scrapes pokemon card images
- uses aws rekognition to extract the text
-  update the data base with correct values

In [101]:
df.loc[df['Stage'] == 'bASIC',['Card Name', 'Set Name', 'Stage']]

      Card Name     Set Name  Stage
11891   Yungoos  SM Base Set  bASIC

In [102]:
df.loc[df['Stage'] == 'bASIC','Stage'] = 'Basic'

In [103]:
df.loc[df['Is Pokemon'] == True, :]['Stage'].unique()

array(['Basic', 'Stage 1', 'BREAK Evolution', 'Stage 2', 'Mega',
       'Mega Evolution', 'Restored', 'VMAX', 'Gigantamax', 'Level Up',
       'Baby', 'Legend', 'Primal', '2', '1', 'Basic — Ultra Beast'],
      dtype=object)

## checking to see what makes pokemon cards unique

This is how a pokemon card will be referenced later on

Card name, set and number are all needed to identify a unique pokemon
This is shown by combining the keys tags together to see if they produce a unique string equal to the total amount of pokemon

In [104]:
df.isna().sum()

index                      0
Card Name                  0
Set Name                   0
Card Number               99
Rarity                     0
Card Type                325
HP                      2124
Stage                   2140
Card Text               9242
Attack 1                2190
Weakness                2672
Resistance              5170
Retreat Cost            2615
Market Price Foil       2146
Median Price Foil       2146
Url                        0
Scraped Date               0
Market Price Normal     4638
Median Price Normal     4638
Attack 2                6782
                       13813
Attack 3               13954
Attack 4               14308
Is Pokemon                 0
dtype: int64

In [105]:
unique_id = df['Card Name'].map(str) + df['Set Name'].map(str)
pokemon_id_uniq = len(unique_id.unique())
total_cards = len(unique_id)
print(f'There are a total of {total_cards} pokemon and combining card name and set name there are {pokemon_id_uniq}')

There are a total of 14311 pokemon and combining card name and set name there are 14167

In [106]:
unique_id = df['Card Name'].map(str) + df['Card Number'].map(str)
pokemon_id_uniq = len(unique_id.unique())
total_cards = len(unique_id)
print(f'There are a total of {total_cards} pokemon and combining card name and card number there are {pokemon_id_uniq}')

There are a total of 14311 pokemon and combining card name and card number there are 13493

In [107]:
unique_id = df['Card Name'].map(str) + df['Set Name'].map(str) + df['Card Number'].map(str)
pokemon_id_uniq = len(unique_id.unique())
total_cards = len(unique_id)
print(f'There are a total of {total_cards} pokemon and combining card name, set name and card number there are {pokemon_id_uniq}')

There are a total of 14311 pokemon and combining card name, set name and card number there are 14311

In [108]:
df['Card Id'] = df['Card Name'].map(str) + df['Set Name'].map(str) + df['Card Number'].map(str)

### Combining data: pokemon cards df and set names df

In [109]:
pc_set = set(df['Set Name']) # there are some weird name conventions that are going to need to be renamed
pokemon_set = set(pokemon_set_df['Set Name']) # this the benchmark for what a set name should look like

In [110]:
print(f'There are {len(pokemon_set - pc_set)} missing or mislabeled sets in the pokemon set df and not from tcgplayer')

There are 44 missing or mislabeled sets in the pokemon set df and not from tcgplayer

In [111]:
print(f'There are {len(pc_set- pokemon_set)} missing or mislabeled sets in the pokemon set df and not from tcgplayer')

There are 100 missing or mislabeled sets in the pokemon set df and not from tcgplayer

## Differences in set names
In some cases prefix like EX are added. In others Series prefix like XY or SM are deleted.
The is no clear order and will need to be monitored when a new expansion is released

In [112]:
sets_dic = {
    'Crystal Guardians':'EX Crystal Guardians',
    'Delta Species':'EX Delta Species',
    'Deoxys':'EX Deoxys',
    'Dragon':'EX Dragon',
    'Dragon Frontiers':'EX Dragon Frontiers',
    'Emerald':'EX Emerald',
    'FireRed & LeafGreen':'EX FireRed and LeafGreen',
    'Hidden Legends':'EX Hidden Legends',
    'Holon Phantoms':'EX Holon Phantoms',
    'Legend Maker':'EX Legend Maker',
    'Power Keepers':'EX Power Keepers',
    'Ruby and Sapphire':'EX Ruby and Sapphire',
    'Sandstorm':'EX Sandstorm',
    'Team Magma vs Team Aqua':'EX Team Magma vs Team Aqua',
    'Team Rocket Returns':'EX Team Rocket Returns',
    'Unseen Forces':'EX Unseen Forces',
    'XY Base Set':'XY',
    'SM Base Set':'Sun and Moon',
    'HeartGold SoulSilver':'HeartGold and SoulSilver',
    'Expedition':'Expedition Base Set',
    'XY - Ancient Origins':'Ancient Origins',
    'XY - BREAKpoint':'BREAKpoint',
    'XY - BREAKthrough':'BREAKthrough',
    'SM - Burning Shadows':'Burning Shadows',
    'SM - Celestial Storm':'Celestial Storm',
    'SM - Crimson Invasion':'Crimson Invasion',
    'XY - Evolutions':'Evolutions',
    'XY - Fates Collide':'Fates Collide',
    'XY - Flashfire':'Flashfire',
    'SM - Forbidden Light':'Forbidden Light',
    'XY - Furious Fists':'Furious Fists',
    'SM - Guardians Rising':'Guardians Rising',
    'SM - Lost Thunder':'Lost Thunder',
    'XY - Phantom Forces':'Phantom Forces',
    'XY - Primal Clash':'Primal Clash',
    'XY - Roaring Skies':'Roaring Skies',
    'XY - Steam Siege':'Steam Siege',
    'SM - Team Up':'Team Up',
    'SM - Ultra Prism':'Ultra Prism',
    'SM - Unbroken Bonds':'Unbroken Bonds',
    'SM - Unified Minds':'Unified Minds',
    'SM - Cosmic Eclipse':'Cosmic Eclipse',
    'SWSH01: Sword & Shield Base Set':'Sword and Shield',
    }
df['Set Name'].replace(sets_dic, inplace = True)
pc_set = set(df['Set Name'])
pokemon_set - pc_set # should be empty or is the latest set that name has been announced, but not the pokemon cards

{'Rebel Clash'}

In [113]:
print(f'There are {len(pokemon_set - pc_set)} missing sets in the pokemon set df and not from tcgplayer')

There are 1 missing sets in the pokemon set df and not from tcgplayer

In [114]:
not_expansion = pd.DataFrame(list(pc_set - pokemon_set),columns = ['Set Name']) # investigating this sets show that they are promotion, tournament winning cards, error cards
not_expansion

                                             Set Name
0                 BW Trainer Kit: Excadrill & Zoroark
1                                        POP Series 6
2                    SWSH: Sword & Shield Promo Cards
3                                        POP Series 1
4             XY Trainer Kit: Pikachu Libre & Suicune
5                                Alternate Art Promos
6                              Black and White Promos
7   SM Trainer Kit: Alolan Sandslash & Alolan Nine...
8                              McDonald's Promos 2019
9                                        Dragon Vault
10                  EX Trainer Kit 1: Latias & Latios
11                                 Blister Exclusives
12                   EX Trainer Kit 2: Plusle & Minun
13                                             Rumble
14                                      Double Crisis
15                    XY Trainer Kit: Latias & Latios
16                             McDonald's Promos 2017
17                                     Best of Promos
18                             DP Training Kit 1 Gold
19                                          SM Promos
20                                       POP Series 2
21                  XY Trainer Kit: Sylveon & Noivern
22                                 Burger King Promos
23                                       POP Series 9
24                             McDonald's Promos 2014
25                                         WoTC Promo
26                    Pikachu World Collection Promos
27                                       POP Series 7
28                                          XY Promos
29                                       POP Series 4
30                          Countdown Calendar Promos
31                                       POP Series 5
32            Legendary Treasures: Radiant Collection
33                                   Southern Islands
34                                        HGSS Promos
35                             McDonald's Promos 2018
36                                        Jumbo Cards
37                                       POP Series 8
38                    Generations: Radiant Collection
39           SM Trainer Kit: Lycanroc & Alolan Raichu
40                     Miscellaneous Cards & Products
41                                  Kalos Starter Set
42                HGSS Trainer Kit: Gyarados & Raichu
43                                    Nintendo Promos
44                              Base Set (Shadowless)
45                                       POP Series 3
46                             McDonald's Promos 2015
47                                    Deck Exclusives
48                        League & Championship Cards
49                                  EX Battle Stadium
50                           Professor Program Promos
51                             DP Training Kit 1 Blue
52                          Hidden Fates: Shiny Vault
53                  DP Trainer Kit: Manaphy & Lucario
54                           Diamond and Pearl Promos
55               XY Trainer Kit: Bisharp & Wigglytuff
56                                     Kids WB Promos

In [115]:
pokemon_set_table = pokemon_set_df.append(not_expansion, sort = False)
pokemon_set_table.reset_index()

     index                              Set Name           Set Date Set Abr
0        0                              Base Set    January 9, 1999      BS
1        1                                Jungle      June 16, 1999      JU
2        2                                Fossil   October 10, 1999      FO
3        3                            Base Set 2  February 24, 2000      B2
4        4                           Team Rocket     April 24, 2000      TR
..     ...                                   ...                ...     ...
141     52             Hidden Fates: Shiny Vault                NaN     NaN
142     53     DP Trainer Kit: Manaphy & Lucario                NaN     NaN
143     54              Diamond and Pearl Promos                NaN     NaN
144     55  XY Trainer Kit: Bisharp & Wigglytuff                NaN     NaN
145     56                        Kids WB Promos                NaN     NaN

[146 rows x 4 columns]

In [116]:
pokemon_set_2 = set(pokemon_set_table['Set Name'])
print(f'There are {len(pc_set- pokemon_set_2)} missing or mislabeled sets in the pokemon set df and not from tcgplayer')

There are 0 missing or mislabeled sets in the pokemon set df and not from tcgplayer

### combining data: pokemon cards df and pokemon names df

### Getting all the pokemon in the pokemon cards
filter by stage name and put a is pokemon check
filter by if name is in a pokedex. If it is not empty put a is pokemon2 check

In [117]:
pokemon_teams = []
generic_name = pokemon_list_df['Pokemon Name'].str.lower().values # contains full name of all pokemon
for pokemon_name in df['Card Name'].values:
    pokemon_team = []
    pokemon_name_clean = re.sub(r'(\(.*\))', '', pokemon_name) # removes the (filler card info) out of cards that may have unrelated pokemon in it
    pokemon_name_clean_list = pokemon_name_clean.lower().split(' ')
    
    pokemon_team = set() 
    for ele1, ele2 in zip_longest(pokemon_name_clean_list[:], pokemon_name_clean_list[1:]):
        if ele1 in generic_name: # a string returns true in a list if exact match. so mr.is not in a list with ['mr. mime']
            pokemon_team.add(ele1)
        if ele2 in generic_name:
            pokemon_team.add(ele2)
        if str(ele1) + ' ' + str(ele2) in generic_name: # this deals with mr. mime/ mime jr. and other pokemon with multiple words
            pokemon_team.add(str(ele1) + ' ' + str(ele2))
    pokemon_teams.append(pokemon_team)

In [118]:
temp = pd.DataFrame(pokemon_teams, columns=['Pokemon 1', 'Pokemon 2', 'Pokemon 3'])
temp.fillna(value=np.nan, inplace=True)

In [123]:
df = pd.concat([df, temp], axis=1)

In [124]:
df.head(3)

,index,Card Name,Set Name,Card Number,Rarity,Card Type,HP,Stage,Card Text,Attack 1,...,Median Price Normal,Attack 2,,Attack 3,Attack 4,Is Pokemon,Card Id,Pokemon 1,Pokemon 2,Pokemon 3
0,0,Zamazenta V (Secret),Sword and Shield,212/202,Secret Rare,Metal,230.0,Basic,Ability — Dauntless ShieldPrevent all damage d...,[1MM] Assault Tackle (130)Discard a Special En...,...,NaN,NaN,NaN,NaN,NaN,True,Zamazenta V (Secret)SWSH01: Sword & Shield Bas...,zamazenta,NaN,NaN
1,1,Water Energy (2004-2005),Professor Program Promos,106/109,Promo,Energy,NaN,NaN,NaN,NaN,...,$19.97,NaN,NaN,NaN,NaN,False,Water Energy (2004-2005)Professor Program Prom...,NaN,NaN,NaN
2,2,Zangoose,Call of Legends,39,Rare,Colorless,80.0,Basic,NaN,"[1] Swords Dance - During your next turn, Zang...",...,$0.65,[3] Lost Claw (30) Choose 1 card from your opp...,NaN,NaN,NaN,True,ZangooseCall of Legends39,zangoose,NaN,NaN

In [125]:
not_pokemon = df['Is Pokemon']==False
has_pokemon = ~df['Pokemon 1'].isna()
bool_combined1 = has_pokemon & not_pokemon

In [127]:
# list of cards to drop from the pokemon 1
# they are cards that are not a pokemon but have a pokemon card in their name
df[bool_combined1]

,index,Card Name,Set Name,Card Number,Rarity,Card Type,HP,Stage,Card Text,Attack 1,...,Median Price Normal,Attack 2,,Attack 3,Attack 4,Is Pokemon,Card Id,Pokemon 1,Pokemon 2,Pokemon 3
176,176,Sharpedo Spirit Link,XY Promos,XY201,Promo,Tool,NaN,NaN,Your turn does not end if the Pokemon this car...,NaN,...,$1.13,NaN,NaN,NaN,NaN,False,Sharpedo Spirit LinkXY PromosXY201,sharpedo,NaN,NaN
179,179,Salamence Spirit Link,XY Promos,XY172,Promo,Tool,NaN,NaN,Your turn does not end if the Pokemon this car...,NaN,...,$2.95,NaN,NaN,NaN,NaN,False,Salamence Spirit LinkXY PromosXY172,salamence,NaN,NaN
218,218,Mawile Spirit Link,XY Promos,XY105,Promo,Tool,NaN,NaN,Attach a Pokemon Tool to 1 of your Pokemon tha...,NaN,...,$0.89,NaN,NaN,NaN,NaN,False,Mawile Spirit LinkXY PromosXY105,mawile,NaN,NaN
247,247,Lucario Spirit Link,XY Promos,XY211,Promo,Tool,NaN,NaN,Your turn does not end if the Pokemon this car...,NaN,...,$0.45,NaN,NaN,NaN,NaN,False,Lucario Spirit LinkXY PromosXY211,lucario,NaN,NaN
297,297,Garchomp Spirit Link,XY Promos,XY169,Promo,Tool,NaN,NaN,Your turn does not end if the Pokemon this car...,NaN,...,$12.87,NaN,NaN,NaN,NaN,False,Garchomp Spirit LinkXY PromosXY169,garchomp,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12396,12397,Slowbro Spirit Link,Evolutions,86,Uncommon,Tool,NaN,NaN,Attach a Pokemon Tool to 1 of your Pokemon tha...,NaN,...,$0.20,NaN,NaN,NaN,NaN,False,Slowbro Spirit LinkXY - Evolutions86,slowbro,NaN,NaN
12414,12415,Pidgeot Spirit Link,Evolutions,81,Uncommon,Tool,NaN,NaN,Attach a Pokemon Tool to 1 of your Pokemon tha...,NaN,...,$0.19,NaN,NaN,NaN,NaN,False,Pidgeot Spirit LinkXY - Evolutions81,pidgeot,NaN,NaN
12484,12485,Charizard Spirit Link,Evolutions,75,Uncommon,Tool,NaN,NaN,Attach a Pokemon Tool to 1 of your Pokemon tha...,NaN,...,$0.20,NaN,NaN,NaN,NaN,False,Charizard Spirit LinkXY - Evolutions75,charizard,NaN,NaN
12491,12492,Blastoise Spirit Link,Evolutions,73,Uncommon,Tool,NaN,NaN,Attach a Pokemon Tool to 1 of your Pokemon tha...,NaN,...,$0.20,NaN,NaN,NaN,NaN,False,Blastoise Spirit LinkXY - Evolutions73,blastoise,NaN,NaN
14278,14279,Gengar Spirit Link - 95/119 (Alternate Holo) (...,Miscellaneous Cards & Products,95,Promo,Item,NaN,NaN,Your turn does not end if the Pokémon this car...,NaN,...,NaN,NaN,NaN,NaN,NaN,False,Gengar Spirit Link - 95/119 (Alternate Holo) (...,gengar,NaN,NaN

In [128]:
df.loc[bool_combined,['Pokemon 1']] = np.nan

In [129]:
is_pokemon = df['Is Pokemon']==True
has_pokemon = df['Pokemon 1'].isna()
bool_combined = is_pokemon & has_pokemon

In [132]:
df[bool_combined]

,index,Card Name,Set Name,Card Number,Rarity,Card Type,HP,Stage,Card Text,Attack 1,...,Median Price Normal,Attack 2,,Attack 3,Attack 4,Is Pokemon,Card Id,Pokemon 1,Pokemon 2,Pokemon 3
373,373,Ash-Greninja EX,XY Promos,XY133,Promo,Water,170.0,Basic,NaN,[1W] Dancing ShurikenFlip 3 coins. This attack...,...,NaN,[1WW] Ninja Blade (130)This Pokemon can't use ...,NaN,NaN,NaN,True,Ash-Greninja EXXY PromosXY133,NaN,NaN,NaN
2883,2883,Buried Fossil,Skyridge,47,Common,Colorless,30.0,Basic,Poke-POWER Reconstruction Once during your tur...,NaN,...,$5.66,NaN,NaN,NaN,NaN,True,Buried FossilSkyridge47,NaN,NaN,NaN
10202,10203,Ash-Greninja EX (XY Black Star Promos),Jumbo Cards,XY133,Promo,Water,170.0,Basic,NaN,[1W] Dancing ShurikenFlip 3 coins. This attack...,...,NaN,[1WW] Ninja Blade (130)This Pokemon can't use ...,NaN,NaN,NaN,True,Ash-Greninja EX (XY Black Star Promos)Jumbo Ca...,NaN,NaN,NaN
10210,10211,______'s Tepid,Jumbo Cards,N/A,Promo,Fire,200.0,Basic,NaN,[R][R][R] _______________ (200)Discard all [R]...,...,NaN,NaN,NaN,NaN,NaN,True,______'s TepidJumbo CardsN/A,NaN,NaN,NaN
10312,10313,Nidoran (F),Primal Clash,66,Common,Psychic,60.0,Basic,NaN,[1] Scratch (10),...,$0.21,[P1] Bite (20),NaN,NaN,NaN,True,Nidoran (F)XY - Primal Clash66,NaN,NaN,NaN
13995,13996,Wobbuffett,Lost Thunder,93,Rare,Psychic,110.0,Basic,Ability — Shady TailAs long as this Pokemon is...,"[1P] Knock Away (30)Flip a coin. If heads, thi...",...,$0.39,NaN,NaN,NaN,NaN,True,WobbuffettSM - Lost Thunder93,NaN,NaN,NaN

In [134]:
df.loc[bool_combined,['Is Pokemon']] = False

## Give each pokemon a pokedex value

In [135]:
pokemon_list_df['Pokedex Id'] = pd.Series(np.arange(1,len(pokemon_list_df)+1,dtype ='int'))

In [136]:
pokemon_list_df['Pokemon Name'] = pokemon_list_df['Pokemon Name'].str.lower()

In [137]:
keys = pokemon_list_df['Pokemon Name'].to_list()
values = pokemon_list_df['Pokedex Id'].to_list()
pokemon_number_mapping = dict(zip(keys, values))

In [138]:
df['Pokedex 1'] = df['Pokemon 1'].map(pokemon_number_mapping)
df['Pokedex 2'] = df['Pokemon 2'].map(pokemon_number_mapping)
df['Pokedex 3'] = df['Pokemon 3'].map(pokemon_number_mapping)

### Snap shot data is complete

In [139]:
df.head()

,index,Card Name,Set Name,Card Number,Rarity,Card Type,HP,Stage,Card Text,Attack 1,...,Attack 3,Attack 4,Is Pokemon,Card Id,Pokemon 1,Pokemon 2,Pokemon 3,Pokedex 1,Pokedex 2,Pokedex 3
0,0,Zamazenta V (Secret),Sword and Shield,212/202,Secret Rare,Metal,230.0,Basic,Ability — Dauntless ShieldPrevent all damage d...,[1MM] Assault Tackle (130)Discard a Special En...,...,NaN,NaN,True,Zamazenta V (Secret)SWSH01: Sword & Shield Bas...,zamazenta,NaN,NaN,889.0,NaN,NaN
1,1,Water Energy (2004-2005),Professor Program Promos,106/109,Promo,Energy,NaN,NaN,NaN,NaN,...,NaN,NaN,False,Water Energy (2004-2005)Professor Program Prom...,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Zangoose,Call of Legends,39,Rare,Colorless,80.0,Basic,NaN,"[1] Swords Dance - During your next turn, Zang...",...,NaN,NaN,True,ZangooseCall of Legends39,zangoose,NaN,NaN,335.0,NaN,NaN
3,3,Zorua,Black and White,70,Common,Darkness,60.0,Basic,NaN,"[2] Lunge (30) Flip a coin. If tails, this at...",...,NaN,NaN,True,ZoruaBlack and White70,zorua,NaN,NaN,570.0,NaN,NaN
4,4,Zorua,Emerging Powers,66,Common,Darkness,50.0,Basic,NaN,[D] Ram (10),...,NaN,NaN,True,ZoruaEmerging Powers66,zorua,NaN,NaN,570.0,NaN,NaN

## Saving the snapshot to an S3 Bucket

The files will be stored in a S3 bucket in the from of 
> s3://pokemon_cards_warehouse/snapshots/filename_date

> S3://pokemon_cards_warehouse/card_prices


Will store snapshot as S3 and then move to S3 Glacier after data has been processed

In [36]:
import boto3

In [ ]:
# import boto3
# s3 = boto3.client('s3')
# bucket = s3.create_bucket(Bucket='pokemon_cards_warehouse')